CREATE DATABASE IF NOT EXISTS `dnscheckup`;
USE `dnscheckup`;
CREATE TABLE IF NOT EXISTS `Session` (
	`id` VARCHAR(64) NOT NULL PRIMARY KEY,
	`language` VARCHAR(16) NOT NULL DEFAULT '',
	`function` VARCHAR(32) NOT NULL DEFAULT '',
	`last_ip` VARCHAR(16) NOT NULL DEFAULT '',
    	`created` DATETIME NOT NULL DEFAULT 0,
    	`last_updated` DATETIME NOT NULL DEFAULT 0,	
	`parameters` VARCHAR(1024) NOT NULL DEFAULT ''
);
